apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: qum1z0v95-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/qum1z0v95-java-springboot-gitops